services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"